version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: serasa-test-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: serasa-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
  app:
    depends_on:
      - postgres
    build: ./
    container_name: serasa-test-nodejs
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
